/**
 * @file LUTSystem.js
 * @description Handles the parsing, generation, and application of 3D Look-Up Tables (LUTs).
 * This system conforms to the industry-standard Adobe .CUBE specification for color grading transport.
 * [Image of 3D LUT color cube mapping]
 */

/**
 * PARSER: Reads a string payload and determines if it is a LUMAFORGE JSON project 
 * or a standard Adobe .CUBE file, then parses it accordingly.
 * @param {string} text - The raw text content of the uploaded file.
 * @returns {Object} { type: 'PROJECT' | 'LUT', data: Object }
 */
export const parseLutFile = (text) => {
    // 1. PROJECT FILE INTERCEPTION
    // LumaForge allows users to save JSON projects with a .cube extension to bypass 
    // strict OS file-pickers. We attempt to parse as JSON first.
    try {
        const json = JSON.parse(text);
        if (json.settings || json.crop) {
            return { type: 'PROJECT', data: json.settings || json };
        }
    } catch (e) {
        // Not a JSON project, proceed to parse as standard .CUBE matrix
    }

    // 2. ADOBE .CUBE FORMAT PARSER
    const lines = text.split('\n');
    let size = 33; // Industry default 3D grid size (33x33x33)
    const data = [];

    for (let line of lines) {
        line = line.trim();
        // Skip empty lines and comments
        if (!line || line.startsWith('#')) continue;

        // Extract matrix dimension bounds
        if (line.startsWith('LUT_3D_SIZE')) {
            size = parseInt(line.split(' ')[1], 10);
        } 
        // Extract RGB float values
        else if (line.match(/^[0-9. ]+$/)) {
            const parts = line.split(' ').filter(x => x !== '').map(parseFloat);
            if (parts.length === 3) {
                data.push({ r: parts[0], g: parts[1], b: parts[2] });
            }
        }
    }

    return { type: 'LUT', data: { size, table: data } };
};

/**
 * GENERATOR: Bakes the current LUMAFORGE mathematical state into a transportable 33x33x33 .CUBE file.
 * @param {Object} settings - The current LumaForge state object.
 * @returns {string} The formatted .CUBE text content.
 */
export const generateLutFile = (settings) => {
    const size = 33;
    let content = `# Generated by LUMAFORGE v1.0.0\n`;
    content += `TITLE Lumaforge_Export\n`;
    content += `LUT_3D_SIZE ${size}\n\n`;

    // Helper: Simulates current settings on a single RGB pixel
    // Note: This replicates the grading logic purely for the LUT matrix generation
    const processPixel = (r, g, b) => {
        // 1. TONE MAPPING (Approximation for LUT export)
        const shadowY = 0.0 + ((settings.shadows||0) / 200);
        const highlightY = 1.0 + ((settings.highlights||0) / 200);
        
        const mapTone = (c) => {
            if (c < 0.5) return shadowY + (c / 0.5) * (0.5 - shadowY);
            return 0.5 + ((c - 0.5) / 0.5) * (highlightY - 0.5);
        };
        
        r = mapTone(r); g = mapTone(g); b = mapTone(b);

        // 2. COLOR GRADING (Simple Tint/Temp approximation)
        if (settings.temp > 0) r += settings.temp/200; 
        else b += Math.abs(settings.temp)/200;
        
        // *Future architecture note: To export the FULL complex grading, the exact 
        // 3-way color matrix math from CorePipeline must be replicated here.
        
        return [r, g, b];
    };

    // Construct the 3D Matrix (B -> G -> R iteration order is strictly required by the .CUBE spec)
    for (let b = 0; b < size; b++) {
        for (let g = 0; g < size; g++) {
            for (let r = 0; r < size; r++) {
                // Generate Identity Coordinates (0.0 to 1.0)
                let ir = r / (size - 1);
                let ig = g / (size - 1);
                let ib = b / (size - 1);

                // Pass Identity Coordinates through the mathematical modifiers
                const [or, og, ob] = processPixel(ir, ig, ib);

                // Format to 6 decimal places as per spec
                content += `${or.toFixed(6)} ${og.toFixed(6)} ${ob.toFixed(6)}\n`;
            }
        }
    }

    return content;
};

/**
 * RENDERER: Applies a parsed 3D LUT to a single RGB pixel in real-time.
 * @param {number} r - Red channel (0-255)
 * @param {number} g - Green channel (0-255)
 * @param {number} b - Blue channel (0-255)
 * @param {Object} lutData - Parsed LUT object containing size and table array
 * @returns {Array<number>} Transformed [R, G, B] values (0-255)
 */
export const applyLutToPixel = (r, g, b, lutData) => {
    if (!lutData || !lutData.table) return [r, g, b];

    const size = lutData.size;
    const data = lutData.table;
    
    // Scale standard 8-bit space (0-255) to the LUT Index Space (e.g., 0-32)
    const scale = (size - 1) / 255;
    const ri = r * scale;
    const gi = g * scale;
    const bi = b * scale;

    // INTERPOLATION: Simplified to Nearest Neighbor for O(1) WebGL/Canvas performance.
    // A full cinematic implementation would use Trilinear Interpolation (averaging 8 neighboring points).
    // Nearest neighbor is computationally cheaper and visually acceptable for real-time web previews.
    const rIdx = Math.round(ri);
    const gIdx = Math.round(gi);
    const bIdx = Math.round(bi);

    // Calculate 1D flat array index from 3D coordinates
    const index = rIdx + gIdx * size + bIdx * size * size;
    
    if (index >= 0 && index < data.length) {
        const val = data[index];
        return [val.r * 255, val.g * 255, val.b * 255]; // Scale float back to 8-bit
    }

    return [r, g, b];
};