/**
 * @file LUTSystem.js
 * @description Handles the parsing, generation, and application of 3D Look-Up Tables (LUTs).
 * This system conforms to the industry-standard Adobe .CUBE specification for color grading transport,
 * while utilizing steganographic comments to store Lumaforge UI state data.
 */

/**
 * PARSER: Reads a string payload and determines if it is a LUMAFORGE Smart LUT, 
 * a legacy JSON project, or a standard third-party Adobe .CUBE file.
 * @param {string} text - The raw text content of the uploaded file.
 * @returns {Object} { type: 'PROJECT' | 'LUT', data: Object }
 */
export const parseLutFile = (text) => {
    // 1. SMART LUT INTERCEPTION (LUMAFORGE PAYLOAD)
    const payloadMatch = text.match(/# LUMAFORGE_STATE:(.+)/);
    
    if (payloadMatch && payloadMatch[1]) {
        try {
            const extractedSettings = JSON.parse(payloadMatch[1].trim());
            console.log("[LUMAFORGE_LUT] Smart Payload detected. Restoring exact UI State.");
            return { type: 'PROJECT', data: extractedSettings };
        } catch (e) {
            console.warn("[LUMAFORGE_LUT] Smart Payload corrupted. Falling back to standard LUT parse.");
        }
    }

    // 2. LEGACY JSON PROJECT INTERCEPTION
    try {
        const json = JSON.parse(text);
        if (json.settings || json.crop) {
            return { type: 'PROJECT', data: json.settings || json };
        }
    } catch (e) {
        console.warn("[LUMAFORGE_LUT] Legacy JSON Project corrupted. Falling back to standard LUT parse.");
    }

    // 3. ADOBE .CUBE FORMAT PARSER (Standard Fallback)
    const lines = text.split('\n');
    let size = 33;
    const data = [];

    for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith('#')) continue;

        if (line.startsWith('LUT_3D_SIZE')) {
            size = parseInt(line.split(' ')[1], 10);
        }
        else if (line.match(/^[0-9. \-]+$/)) {
            const parts = line.split(' ').filter(x => x !== '').map(parseFloat);
            if (parts.length === 3) {
                data.push({ r: parts[0], g: parts[1], b: parts[2] });
            }
        }
    }

    return { type: 'LUT', data: { size, table: data } };
};

/**
 * GENERATOR: Bakes the current LUMAFORGE mathematical state into a transportable 33x33x33 .CUBE file,
 * injecting the exact UI settings into the header block.
 * @param {Object} settings - The current LumaForge state object.
 * @returns {string} The formatted .CUBE text content.
 */
export const generateLutFile = (settings) => {
    const size = 33;
    let content = `# Generated by LUMAFORGE v1.2.0\n`;

    content += `# LUMAFORGE_STATE:${JSON.stringify(settings)}\n`;
    
    content += `TITLE "Lumaforge_Export"\n`;
    content += `LUT_3D_SIZE ${size}\n\n`;

    const processPixel = (r, g, b) => {
        // 1. TONE MAPPING (Approximation for LUT export)
        const shadowY = 0.0 + ((settings.shadows||0) / 200);
        const highlightY = 1.0 + ((settings.highlights||0) / 200);
        
        const mapTone = (c) => {
            if (c < 0.5) return shadowY + (c / 0.5) * (0.5 - shadowY);
            return 0.5 + ((c - 0.5) / 0.5) * (highlightY - 0.5);
        };
        
        r = mapTone(r); g = mapTone(g); b = mapTone(b);

        // 2. COLOR GRADING (Simple Tint/Temp approximation)
        if (settings.temp > 0) r += settings.temp/200; 
        else b += Math.abs(settings.temp)/200;
        
        return [r, g, b];
    };

    for (let b = 0; b < size; b++) {
        for (let g = 0; g < size; g++) {
            for (let r = 0; r < size; r++) {
                let ir = r / (size - 1);
                let ig = g / (size - 1);
                let ib = b / (size - 1);

                const [or, og, ob] = processPixel(ir, ig, ib);

                content += `${or.toFixed(6)} ${og.toFixed(6)} ${ob.toFixed(6)}\n`;
            }
        }
    }

    return content;
};

/**
 * RENDERER: Applies a parsed 3D LUT to a single RGB pixel in real-time.
 * @param {number} r - Red channel (0-255)
 * @param {number} g - Green channel (0-255)
 * @param {number} b - Blue channel (0-255)
 * @param {Object} lutData - Parsed LUT object containing size and table array
 * @returns {Array<number>} Transformed [R, G, B] values (0-255)
 */
export const applyLutToPixel = (r, g, b, lutData) => {
    if (!lutData || !lutData.table) return [r, g, b];

    const size = lutData.size;
    const data = lutData.table;

    const scale = (size - 1) / 255;
    const ri = r * scale;
    const gi = g * scale;
    const bi = b * scale;

    const rIdx = Math.round(ri);
    const gIdx = Math.round(gi);
    const bIdx = Math.round(bi);

    const index = rIdx + gIdx * size + bIdx * size * size;
    
    if (index >= 0 && index < data.length) {
        const val = data[index];
        return [val.r * 255, val.g * 255, val.b * 255];
    }

    return [r, g, b];
};