/**
 * @file MetadataSystem.js
 * @description Steganographic engine for reading and writing LumaForge project data 
 * invisibly inside PNG files. Conforms to the ISO/IEC 15948 PNG specification.
 */

/**
 * Calculates a Cyclic Redundancy Check (CRC-32) checksum.
 * Required by the PNG specification to validate chunk data integrity.
 * @param {Uint8Array} buf - The buffer containing the Chunk Type and Chunk Data.
 * @returns {number} The 32-bit CRC hash.
 */
const crc32 = (buf) => {
    const table = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
        let c = i;
        for (let k = 0; k < 8; k++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
        table[i] = c;
    }
    let crc = -1;
    for (let i = 0; i < buf.length; i++) {
        crc = (crc >>> 8) ^ table[(crc ^ buf[i]) & 0xFF];
    }
    return (crc ^ -1) >>> 0;
};

/**
 * INJECTOR: Encodes the application state into a custom tEXt chunk and splices it 
 * into the binary of the final image before the physical file is downloaded.
 * 
 * @param {Blob} imageBlob - The raw PNG blob generated by the canvas.
 * @param {Object} settings - The payload to be injected (LumaForge Project State).
 * @returns {Promise<Blob>} A new PNG Blob containing the hidden metadata.
 */
export const injectMetadata = async (imageBlob, settings) => {
    const buffer = await imageBlob.arrayBuffer();
    const uint8 = new Uint8Array(buffer);

    // 1. DATA PREPARATION (Keyword + Null + Text)
    const keyword = "LumaForge_Data";
    const text = JSON.stringify(settings);
    
    // Utilize TextEncoder for safe UTF-8 byte conversion
    const encoder = new TextEncoder();
    const keyBytes = encoder.encode(keyword);
    const textBytes = encoder.encode(text);
    
    // PNG tEXt Chunk Data Length = Keyword + Null Separator (1 byte) + Text
    const dataLen = keyBytes.length + 1 + textBytes.length;
    
    // Construct the [Type + Data] block strictly for the CRC32 calculation
    const chunkBlock = new Uint8Array(4 + dataLen);
    
    // Write Chunk Type: 'tEXt' (ASCII: 116, 69, 88, 116)
    chunkBlock.set([116, 69, 88, 116], 0); 
    
    // Write Keyword payload
    chunkBlock.set(keyBytes, 4);
    
    // Write Null Separator (0x00)
    chunkBlock[4 + keyBytes.length] = 0;
    
    // Write JSON Text payload
    chunkBlock.set(textBytes, 4 + keyBytes.length + 1);

    // Calculate CRC checksum on the assembled [Type + Data] block
    const crcVal = crc32(chunkBlock);

    // 2. FIND INSERTION POINT (Just before the IEND Chunk)
    let iendIdx = -1;
    // Scan backwards for the IEND signature (0x49 0x45 0x4E 0x44)
    for (let i = uint8.length - 8; i >= 0; i--) {
        if (uint8[i] === 0x49 && uint8[i+1] === 0x45 && uint8[i+2] === 0x4E && uint8[i+3] === 0x44) {
            iendIdx = i - 4; // Set index to the start of the IEND Length bytes
            break;
        }
    }
    
    // Failsafe: If IEND is missing (corrupt PNG), abort injection and return raw blob
    if (iendIdx === -1) return imageBlob; 

    // 3. ASSEMBLE FINAL BLOB
    // Structure: [Original PNG Data up to IEND] + [Our Data Length] + [Our Chunk] + [Our CRC] + [IEND Chunk]
    
    const lenArr = new Uint8Array(4);
    new DataView(lenArr.buffer).setUint32(0, dataLen, false); // Length dictates Data size only

    const crcArr = new Uint8Array(4);
    new DataView(crcArr.buffer).setUint32(0, crcVal, false);

    const finalBlob = new Blob([
        uint8.slice(0, iendIdx),
        lenArr,
        chunkBlock,
        crcArr,
        uint8.slice(iendIdx)
    ], { type: 'image/png' });

    return finalBlob;
};

/**
 * READER: Scans an uploaded file at the binary level, hopping through PNG chunks 
 * to locate and extract a LumaForge steganographic payload.
 * @param {File} file - The uploaded image file.
 * @returns {Promise<Object|null>} Parsed JSON state object, or null if not found/invalid.
 */
export const readMetadata = async (file) => {
    try {
        const buffer = await file.arrayBuffer();
        const view = new DataView(buffer);
        const uint8 = new Uint8Array(buffer);

        // 1. SIGNATURE CHECK
        // Verifies the file is actually a PNG (0x89 0x50 0x4E 0x47...)
        if (uint8[0] !== 0x89) return null;

        let offset = 8; // Start reading immediately after the 8-byte PNG signature
        const decoder = new TextDecoder();

        // 2. CHUNK-HOPPING LOOP
        while (offset < buffer.byteLength) {
            if (offset + 4 > buffer.byteLength) break;
            
            // Read next Chunk Length (4 bytes)
            const length = view.getUint32(offset, false);
            
            if (offset + 8 > buffer.byteLength) break;
            
            // Read next Chunk Type (4 bytes converted to ASCII string)
            const type = String.fromCharCode(
                uint8[offset + 4], uint8[offset + 5], uint8[offset + 6], uint8[offset + 7]
            );

            // 3. PAYLOAD IDENTIFICATION
            if (type === 'tEXt') {
                const dataStart = offset + 8;
                
                // Keyword is "LumaForge_Data" (14 bytes) + 1 byte Null Separator = 15 bytes min
                if (length > 15) {
                    const checkKeyword = decoder.decode(uint8.slice(dataStart, dataStart + 14));
                    
                    if (checkKeyword === "LumaForge_Data" && uint8[dataStart + 14] === 0) {
                        // PAYLOAD FOUND: Extract JSON string located immediately after the Null Separator
                        const jsonStart = dataStart + 15;
                        const jsonLen = length - 15;
                        const jsonStr = decoder.decode(uint8.slice(jsonStart, jsonStart + jsonLen));
                        
                        console.log("[LUMAFORGE_SYSTEM] Black Box Metadata Extracted.");
                        return JSON.parse(jsonStr);
                    }
                }
            }
            
            // 4. JUMP TO NEXT CHUNK
            // Advance offset by: Length descriptor (4) + Type descriptor (4) + Data (length) + CRC (4)
            offset += 12 + length;
        }
    } catch (e) {
        console.error("[LUMAFORGE_FAULT] Metadata Read Error. Proceeding with clean load:", e);
    }
    
    return null;
};