export const getFreshState = () => ({
  crop: { x: 10, y: 10, width: 80, height: 80, aspect: null },
  cropApplied: false, 
  aspectRatio: 'ORIGINAL', 
  imageDimensions: { w: 0, h: 0, ratio: 1 },
  rotate: 0, 
  flipX: false, 
  flipY: false, 
  zoom: 0,
  exposure: 0, 
  contrast: 0, 
  highlights: 0, 
  shadows: 0, 
  whites: 0, 
  blacks: 0,
  temp: 0, 
  tint: 0, 
  vibrance: 0, 
  saturation: 0, 
  hue: 0, 
  sepia: 0, 
  invert: 0,
  gradingHex: { shadows: "#808080", midtones: "#808080", highlights: "#808080" },
  grading: { 
    shadows: {r:0.5, g:0.5, b:0.5}, 
    midtones: {r:0.5, g:0.5, b:0.5}, 
    highlights: {r:0.5, g:0.5, b:0.5} 
  },
  gradingLum: { shadows: 0, midtones: 0, highlights: 0 },
  gradingBlend: { shadows: 100, midtones: 100, highlights: 100 },
  sharpen: 0, 
  clarity: 0, 
  dehaze: 0, 
  vignette: 0, 
  grainAmount: 0, 
  grainSize: 50, 
  grainRoughness: 50,
  halationAmount: 0, 
  halationThreshold: 0,
  activeLut: null,
  watermark: false,
  curves: { 
    master: [{x:0, y:0}, {x:255, y:255}], 
    red: [{x:0, y:0}, {x:255, y:255}], 
    green: [{x:0, y:0}, {x:255, y:255}], 
    blue: [{x:0, y:0}, {x:255, y:255}] 
  }
});